# Default values for etcd-snapshot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: etcd-snapshot-save
  tag: v0.0.0
  pullPolicy: IfNotPresent

etcd:
  ip:
    - 127.0.0.1
  port: 2379

schedule: "0 0 * * *"

s3:
  endpoint: object-storage-endpoint
  bucket: etcd-snapshots
  secret: object-storage-secret

tls:
  rootCA: ""
  clientCrt: ""
  clientKey: ""
