apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "etcd-snapshot.fullname" . }}
  labels:
    {{- include "etcd-snapshot.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcdctl
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - --cacert=/certs/ca.crt
              - --cert=/certs/client.crt
              - --key=/certs/client.key
              - --endpoints=etcd-snapshot-etcd:2379
              - --s3.endpoint={{ .Values.s3.endpoint }}
              - --s3.bucket={{ .Values.s3.bucket }}
              - --s3.access-key=$(S3_ACCESS_KEY)
              - --s3.secret-key=$(S3_SECRET_KEY)
              {{ if .Values.s3.prefix }}
              - --s3.prefix={{ .Values.s3.prefix }}
              {{ end }}
            env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secret }}
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secret }}
                  key: secretkey
            volumeMounts:
            - mountPath: /certs
              name: certs
          restartPolicy: OnFailure
          volumes:
          - name: certs
            secret:
              secretName: {{ include "etcd-snapshot.fullname" . }}-certs
