apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd-snapshot.fullname" . }}-etcd
  labels:
    {{- include "etcd-snapshot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 2379
    protocol: TCP
    targetPort: 2379
